# Generated by Django 5.2.4 on 2025-07-07 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='job_role',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
