# Generated by Django 5.2.4 on 2025-07-19 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0006_alter_interviewanswer_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InterviewAnswer',
        ),
    ]
